- name: Reset Kubernetes Cluster
  block:
    - name: Reset kubeadm (forcefully)
      command: kubeadm reset -f

    - name: Remove Kubernetes config directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - /etc/cni/net.d
        - /var/lib/cni
        - /var/lib/kubelet
        - /root/.kube
        - /home/{{ ansible_user | default('ubuntu') }}/.kube

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: true

    - name: Fully reset net.ipv4.ip_forward setting
      block:

        - name: Remove Kubernetes sysctl config if exists
          file:
            path: /etc/sysctl.d/k8s.conf
            state: absent

        - name: Re-apply all remaining sysctl settings from disk
          command: sysctl --system
