services:
  spark-worker-etl:
    image: ghcr.io/jmhwang-dev/warehouse:sp3.5.6-ice1.9.1
    container_name: spark-worker-etl
    # network_mode: host
    restart: unless-stopped
    environment:
      - SPARK_WORKER_CORES=12
      - SPARK_WORKER_MEMORY=24g
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./configs/spark:/opt/spark/conf:ro
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://192.168.45.192:7078