[project]
name = "e-commerce"
version = "0.1.0"
description = ""
authors = [
    {name = "jmhwang-dev",email = "jungmin.hwang.dev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.3.0,<3.0.0)",
    "duckdb (>=1.3.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
  { include = "common", from = "src" },
]
[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

