services:
  postgres:
    image: postgres:latest
    container_name: olist-postgres
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: olist
    ports:
      - "5432:5432"
    volumes:
      - ../data/bronze:/mnt/bronze
      - ../data/silver:/mnt/silver
      - ../data/gold:/mnt/gold
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
