src_path: ./artifacts/inference/1_por2eng.txt
dataset_start_index: 0
dataset_end_index: 19051
dst_path: ./artifacts/inference/1_eng2kor.txt
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: auto
initial_batch_size: 9
language_from: English
language_into: Korean
