src_path: ./artifacts/preprocess/reviews_textonly.txt
dataset_start_index: 0
dataset_end_index: 19051
dst_path: ./artifacts/inference/1_por2eng.txt
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: auto
initial_batch_size: 10
language_from: Portuguese
language_into: English
