src_path: ./artifacts/inference/2_por2eng.txt
dataset_start_index: 0
dataset_end_index: 19052
dst_path: ./artifacts/inference/2_eng_senti.csv
checkpoint: j-hartmann/sentiment-roberta-large-english-3-classes
device: cpu
initial_batch_size: 300
