src_path: ./artifacts/inference/2_por2eng.txt
dataset_start_index: 0
dataset_end_index: 19052
dst_path: ./artifacts/inference/2_eng2kor.txt
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: cpu
initial_batch_size: 120
language_from: English
language_into: Korean
