src_path: ./artifacts/inference/por2eng_2.txt
dataset_start_index: 0
dataset_end_index: 19052
dst_path: ./artifacts/inference/eng2kor_2.txt
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: cpu
initial_batch_size: 120
language_from: English
language_into: Korean
