---
- name: Extract {{framework_file.dest}} to {{ install_dir }}/{{ dist_name }}
  become: true
  ansible.builtin.unarchive:
    src: "{{ framework_file.dest }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: framework_file is defined and framework_file.dest is defined