---
framework_name: 'hadoop'
version: 3.4.1
dist_name: "{{framework_name}}-{{ version }}"

home_dir: "{{ install_dir }}/{{ dist_name }}"
base_url: "{{apache_base_url}}/hadoop/common"
targz_name: "{{ dist_name }}.tar.gz"
asc_name: "{{ targz_name }}.asc"
sha512_name: "{{targz_name}}.sha512"

conf_dir: /home/jmhwang/Documents/github/jmhwang-dev/e-commerce/hadoop/conf

# HDFS 데이터 디렉토리
namenode_dir: /mnt/hadoop/dfs/name
datanode_dir: /mnt/hadoop/dfs/data