---
- name: Check if home_dir exists
  ansible.builtin.stat:
    path: "{{ home_dir }}"
  register: home_dir_status

- name: Extract {{framework_file.dest}} to {{ base_install_dir }}
  become: true
  ansible.builtin.unarchive:
    src: "{{ framework_file.dest }}"
    dest: "{{ base_install_dir }}"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: not home_dir_status.stat.exists