---
- name: INSTALL HDFS
  hosts: hdfs_cluster
  roles:
    - common
    # - hdfs
  # tasks:
  #   - name: Ping my hosts
  #     ansible.builtin.ping:

# - name: My second play (Spark 클러스터 메시지 출력)
#   hosts: spark_cluster
#   tasks:
#     - name: Print message
#       ansible.builtin.debug:
#         msg: Hello world