---
all:
  children:
    hdfs_cluster:
      children:
        hadoop_namenodes:
          hosts:
            master: {}
        hadoop_datanodes:
          hosts:
            worker1: {}
            worker2: {}