---
all:
  children:
    cluster_hdfs:
      children:
        client:
          hosts:
            desktop: {}
        namenodes:
          hosts:
            master: {}
        datanodes:
          hosts:
            worker1: {}
            worker2: {}
        
    cluster_k8s:
      children:
        master:
          hosts:
            master: {}
        workers:
          hosts:
            worker1: {}
            worker2: {}