---
all:
  children:
    cluster_hdfs:
      children:
        hadoop_namenodes:
          hosts:
            master: {}
        # hadoop_datanodes:
        #   hosts:
        #     worker1: {}
        #     worker2: {}

    # cluster_spark:
    #   children:
    #     spark_masters:
    #       hosts:
    #         master: {}
    #     spark_workers:
    #       hosts:
    #         worker1: {}
    #         worker2: {}