---
all:
  children:
    cluster_hdfs:
      children:
        client:
          hosts:
            desktop: {}
        namenodes:
          hosts:
            master: {}
        datanodes:
          hosts:
            worker1: {}
            worker2: {}
        
    cluster_spark:
      children:
        spark_masters:
          hosts:
            master: {}
        spark_workers:
          hosts:
            worker1: {}
            worker2: {}