---
- name: INSTALL common packages on all nodes
  hosts: cluster_hdfs
  roles:
    - install

- name: Setup HDFS on namenode(s)
  hosts: namenodes
  become: true
  roles:
    - hdfs

- name: Setup HDFS on datanode(s)
  hosts: datanodes
  become: true
  roles:
    - hdfs
