---
- name: Set up Kubernetes on master
  hosts: master
  become: true
  gather_facts: true

  roles:
  - role: k8s
    vars:
      install_common: true
      install_master: true

- name: Set up Kubernetes on workers
  hosts: workers
  become: true
  gather_facts: true

  roles:
  - role: k8s
    vars:
      install_common: true