---
ansible_user: jmhwang
# Path to the root of this repository. Override when running the playbook from a different
# location.
git_clone_path: "{{ playbook_dir | dirname }}"

java_package: openjdk-8-jdk
jdk_dir_name_pattern: java-8-openjdk*

base_apache_url: https://dlcdn.apache.org

base_download_dir: /tmp
base_install_dir: /opt
