---
- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and install Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{version}}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
# This allow unprivileged APT programs to read this keyring
# This helps tools such as command-not-found to work correctly
- name: Set permissions on Kubernetes GPG key
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

# echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
- name: Overwrite Kubernetes APT repository file
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ version }}/deb/ /"
    mode: '0644'

- name: Install common
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - containerd
      - kubeadm
      - kubelet

    state: latest
    update_cache: yes

# sudo apt-mark hold kubelet kubeadm
- name: "Hold Kubernetes components: kubelet kubeadm"
  shell: apt-mark hold {{ item }}
  loop:
    - kubelet
    - kubeadm

# Configuration
- name: Disable swap temporarily
  command: swapoff -a

- name: Disable swap permanently by editing fstab
  replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\s+swap\s+.*)$'
    replace: '# \1'

- name: Ensure br_netfilter kernel module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter is configured to load on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
    mode: '0644'

- name: Set Kubernetes sysctl parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system

- name: "Configure containerd with SystemdCgroup = true"
  block:
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      command: "containerd config default"
      register: containerd_config

    - name: Write config.toml
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        mode: '0644'

    - name: Set SystemdCgroup = true
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

- name: Enable IP forwarding on all Kubernetes nodes
  block:
    - name: Enable IP forwarding permanently
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1
        mode: '0644'

    - name: Re-apply all remaining sysctl settings from disk
      command: sysctl --system