---
- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and install Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{version}}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
# This allow unprivileged APT programs to read this keyring
# This helps tools such as command-not-found to work correctly
- name: Set permissions on Kubernetes GPG key
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

# echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
- name: Overwrite Kubernetes APT repository file
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ version }}/deb/ /"
    mode: '0644'

- name: Install common
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - containerd

    state: latest
    update_cache: yes