source:
  type: kafka
  config:
    connection:
      bootstrap: '192.168.45.190:19092,192.168.45.190:19094,192.168.45.190:19096'
      schema_registry_url: 'http://192.168.45.190:8082'
    platform_instance: kafka_dev
    env: dev
    disable_topic_record_naming_strategy: true
    topic_subject_map:
      "customer-value": "customer"
      "seller-value": "seller"
      "order_status-value": "order_status"
      "product-value": "product"
      "order_item-value": "order_item"
      "review-value": "review"
      "payment-value": "payment"
      "geolocation-value": "geolocation"
sink:
  type: datahub-rest
  config:
    server: 'http://localhost:8080'